{\rtf1\ansi\ansicpg1252\cocoartf1671\cocoasubrtf600
{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red56\green185\blue199;}
{\*\expandedcolortbl;;\csgray\c0;\cssrgb\c25544\c77008\c82022;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs32 \cf2 \CocoaLigature0         name: net.core.rmem_default\
        value: 16777216\
        state: present\
        reload: yes\
\
\cf3       # Use docker_container module\cf2 \
    - name: download and launch a docker elk container\
      docker_container:\
        name: elk\
        image: sebp/elk:761\
        state: started\
        restart_policy: always\
\cf3         # Please list the ports that ELK runs on\cf2 \
        published_ports:\
          -  5601:5601\
          -  9200:9200\
          -  5044:5044}